### PR TITLE
Day2

### PR DESCRIPTION
**Pull request by brandenclark**

### CODE REVIEW

**Comment by brandenclark** [comment]
@patrik-drean Look good?

**Comment by brandenclark** [comment]
You can just squash and merge instead of responding if you want.

**Comment by patrik-drean** [comment]
I should have looked closer before I just merged it... my bad!

Do we need .gitignores everywhere? The top level one should take care of it for us.

Also, I think there's a normal submissions folder in hw2 that needs to be deleted.

**Comment by brandenclark** [comment]
Oops, forgot to delete that regular submission folder... I added the
underscore so it’s always the top folder no matter which hw folder it’s in.
The .gitignores are the only way I could add the submissions directory
since you can’t add/commit an empty directory to be tracked...

Also, will you check my repo permissions? I can’t go alter or see the
settings in GitHub at all.

**Pull request merged**
